# Generated by Django 2.2 on 2022-06-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerregistrationmodel',
            name='status',
        ),
    ]
