# Generated by Django 2.2 on 2022-06-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_remove_farmerregistrationmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.FarmerRegistrationModel')),
            ],
        ),
    ]
