# Generated by Django 2.2 on 2022-06-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='title',
            field=models.CharField(default=4841199156, max_length=10, unique=True),
        ),
    ]
