# Generated by Django 3.2.12 on 2022-06-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20220611_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='title',
            field=models.CharField(default=4060932815, max_length=10, unique=True),
        ),
    ]
