# Generated by Django 3.2.12 on 2022-06-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_alter_productstatus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='title',
            field=models.CharField(default=8688934972, max_length=10, unique=True),
        ),
    ]
