# Generated by Django 3.2.12 on 2022-06-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_alter_productstatus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAgroProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(choices=[('p1', 'p1'), ('p2', 'p2'), ('p3', 'p3'), ('p4', 'p4'), ('p5', 'p5')], max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='title',
            field=models.CharField(default=5140366229, max_length=10, unique=True),
        ),
    ]
