# Generated by Django 3.2.12 on 2022-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_auto_20220618_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('feedBack', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='title',
            field=models.CharField(default=2051878292, max_length=10, unique=True),
        ),
    ]
