# Generated by Django 3.2.12 on 2022-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_auto_20220618_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='title',
            field=models.CharField(default=5671881883, max_length=10, unique=True),
        ),
    ]
