# Generated by Django 3.2.12 on 2022-06-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeemodel_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='loginId',
            field=models.CharField(auto_created=True, default=287995, max_length=6, unique=True),
        ),
    ]
