# Generated by Django 3.2.12 on 2022-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeemodel_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='loginId',
            field=models.CharField(default=968516, editable=False, max_length=6, unique=True),
        ),
    ]
