# Generated by Django 3.2.12 on 2022-06-18 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeemodel_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 6, 18))),
                ('department', models.CharField(choices=[('dep1', 'dep1'), ('dep2', 'dep2'), ('dep3', 'dep3'), ('dep4', 'dep4'), ('dep5', 'dep5')], max_length=5)),
                ('work', models.CharField(choices=[('work1', 'work1'), ('work2', 'work2'), ('work3', 'work3'), ('work4', 'work4'), ('work5', 'work5')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='loginId',
            field=models.CharField(default=438170, editable=False, max_length=6, unique=True),
        ),
    ]
