# Generated by Django 3.2.12 on 2022-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20220618_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='workupdate',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='loginId',
            field=models.CharField(default=886758, editable=False, max_length=6, unique=True),
        ),
    ]
