# Generated by Django 3.2.12 on 2022-06-18 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20220618_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_test', models.CharField(max_length=255)),
                ('soil_test', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 6, 18))),
                ('other_reports', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='loginId',
            field=models.CharField(default=166221, editable=False, max_length=6, unique=True),
        ),
    ]
